name: Tests

on: pull_request

jobs:
  test:
    name: Run Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install PDM and dependencies
        run: |
          pip install pdm
          pdm config python.use_venv true
          pdm install

      - name: Run pytest
        run: pdm run pytest
